### PR TITLE
[Fix #255] Add new `Minitest/AssertOperator` and `Minitest/RefuteOperator` cops

### LINKED ISSUE #255: Enforce assert_operator instead of assert with operator expression
## Is your feature request related to a problem? Please describe.

When reviewing PRs of teammates using for example `assert(a < b)`

## Describe the solution you'd like

I'd like rubocop to recommend for example `assert_operator(a, :<, b)`

## Additional context

I was surprised I couldn't find this cop, as it seems pretty simple to implement (possibly naively) and it's in the minitest style guide https://github.com/rubocop/minitest-style-guide#assert-operator

Would you accept a PR for a new cop `Minitest/AssertOperator` ?

Thanks

### PR DESCRIPTION
**Pull request by koic**
Fixes #255.

This PR adds new `Minitest/AssertOperator` and `Minitest/RefuteOperator` cops.

## `Minitest/AssertOperator` cop

This cop enforces the use of `assert_operator(expected, :<, actual)` over `assert(expected < actual)`.

```ruby
# bad
assert(expected < actual)

# good
assert_operator(expected, :<, actual)
```

## `Minitest/RefuteOperator` cop

This cop enforces the use of `refute_operator(expected, :<, actual)` over `refute(expected < actual)`.

```ruby
# bad
refute(expected < actual)

# good
refute_operator(expected, :<, actual)
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-minitest/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by GUI** [comment]
@koic: Is it intentional that this triggers for hash access too? I understand the benefits for math operators like in these examples and in the style guide, but these suggestions for hashes seem less idiomatic to me:

```
[Correctable] Minitest/RefuteOperator: Prefer using refute_operator(response.headers, :[], "content-length").
    refute(response.headers["content-length"])

[Correctable] Minitest/AssertOperator: Prefer using assert_operator(data["headers"], :[], "authorization").
    assert(data["headers"]["authorization"])
```

Since I didn't see this type of thing called out in the style guide, I just wasn't sure if this new behavior was intentional or not. Thanks!

**Comment by flavorjones** [comment]
@GUI you may be interested in #264

**Comment by koic** [comment]
I've released 0.32.2 with that change. Thank you!
https://github.com/rubocop/rubocop-minitest/releases/tag/v0.32.2

**Comment by TSMMark** [comment]
This is awesome thanks so much @koic for adding this!

I just ran this across our codebase and discovered an autocorrect which I found interesting:

```ruby
refute(something == something_else)
```

corrected to:

```ruby
refute_operator(something, :==, something_else)
```

, which is expected, of course.

However, I'm surprised the [`Minitest/RefuteEqual`](https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestrefuteequal) cop didn't already report this, and correct to:

```ruby
refute_equal(something, something_else)
```

Is that a missing feature of `Minitest/RefuteEqual`? If so, would you like me to open an issue?

Thanks again

**Comment by koic** [comment]
Thank you for the feedback. I've opened https://github.com/rubocop/rubocop-minitest/pull/265. After this I'll open a PR that will make some more adjustments.

**Pull request merged**
