### PR TITLE
Add new `Minitest/RedundantMessageArgument` cop

### PR DESCRIPTION
**Pull request by koic**
This PR adds new `Minitest/RedundantMessageArgument` cop that detects redundant message argument in assertion methods. The message argument `nil` is redundant because it is the default value.

```ruby
# bad
assert_equal(expected, actual, nil)

# good
assert_equal(expected, actual)
assert_equal(expected, actual, 'message')
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] The PR relates to *only* one subject with a clear title and description in grammatically correct, complete sentences.
* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Ran `bundle exec rake default`. It executes all tests and runs RuboCop on its own code.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-minitest/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by andyw8** [comment]
I'm curious about the context for this, where did you encounter it?

**Comment by koic** [comment]
https://github.com/zdennis/activerecord-import/commit/85cbdea5cc2a759c5224890cef5aada29651646b

**Comment by andyw8** [comment]
I see. I'm wondering if it might be better for this to be in Minitest, e.g. it can raise if `nil` is given for that argument?

**Comment by koic** [comment]
That's an interesting idea. If you're up for it, please propose it to Minitest. 
Regardless, `raise` operates at runtime, while this cop is for static analysis, so the detection timing differs. It shouldn't detract from the value of this cop, I think.

**Pull request merged**
