### PR TITLE
[Fix #155] Provide `assert_offense` and `assert_no_offenses` for custom cop development

### LINKED ISSUE #155: Include `TestHelper` and `AssertionHelper` in the gem
## Is your feature request related to a problem? Please describe.
Within the main Shopify repo, we have several custom cops we'd like to create tests for with Minitest. Having [`TestHelper`](https://github.com/rubocop/rubocop-minitest/blob/master/test/test_helper.rb) and [`AssertionHelper`](https://github.com/rubocop/rubocop-minitest/blob/master/test/assertion_helper.rb) included in the public release of the gem would be greatly helpful for us so we can take advantage of the functionality built here. They're currently inaccessible as they're located inside the `test` directory.

## Describe the solution you'd like
Have [`TestHelper`](https://github.com/rubocop/rubocop-minitest/blob/master/test/test_helper.rb) and [`AssertionHelper`](https://github.com/rubocop/rubocop-minitest/blob/master/test/assertion_helper.rb) bundled in the gem.

## Describe alternatives you've considered
RuboCop has some RSpec helpers which are included in the gem, like [`ExpectOffense`](https://github.com/rubocop/rubocop/blob/ee7ab6dceafa726d3ce936746d10d3eb50e27356/lib/rubocop/rspec/expect_offense.rb). However, it seems like you've already done the work to port it to Minitest, which is exactly what we need.

### PR DESCRIPTION
**Pull request by koic**
Resolves #155.

This PR provides `assert_offense`, `assert_correction`, and `assert_no_offenses` for custom Minitest cop development.

Developers can use these APIs by requesting the following in custom Minitest cop test code:

```ruby
require 'rubocop/minitest/support'
```

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [ ] Added tests.
* [x] Added an entry (file) to the [changelog folder](https://github.com/rubocop/rubocop-minitest/blob/master/changelog/) named `{change_type}_{change_description}.md` if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop/rubocop/blob/master/CONTRIBUTING.md#changelog-entry-format) for details.
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

**Comment by alex4787** [comment]
Thank you very much!

**Comment by koic** [comment]
@alex4787 Yeah, I've just released 0.17.0 :-)
https://github.com/rubocop/rubocop-minitest/releases/tag/v0.17.0

**Comment by alex4787** [comment]
@koic Thanks, appreciate the quick addition! And sorry to tack on another thing, but we were wondering if this could also be included in the main RuboCop gem as well, to provide a Minitest testing option for any custom cop development, not only specific to Minitest-related cops.

**Comment by koic** [comment]
Thank you for sharing your ideas. However, the APIs started with RuboCop Minitest's dogfooding. It wasn't essentially intended to have in the RuboCop core.
https://github.com/rubocop/rubocop-minitest/issues/1#issuecomment-518548748

TBH, it would be undesirable to provide APIs for multiple testing frameworks in the RuboCop core. So, this API focuses on custom RuboCop Minitest development. Thank you.

**Comment by alex4787** [comment]
Got it, thanks for the context here. 😄

**Pull request merged**
